### ISSUE TITLE
Inaccurate costs & images didn't load

### ISSUE THREAD

**Issue by schrottii** [jugh3ad/StarCalc#1]
https://media.discordapp.net/attachments/427135759452209173/845563948128665610/unknown.png?width=402&height=316

As you can see on that image, the images didn't load (Browser: Firefox) and the magnet costs are false.

I calculated from x5200 stars to x5201 and the gs and fragment costs are the exact same as ingame, but magnets is 22.323.032.080 while the calculator says 24.091.693.620.

**Comment by jugh3ad** [comment]
The images have been changed from wiki links to local images.
Corrected an issue where magnet calculations was using decimal values instead of whole numbers.
